name: Genera la imágen y la publica en el hub de Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}        
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
                
      - name: Build and push backend
        id: docker_build_bk
        uses: docker/build-push-action@v2
        with:
          context: ./backend/aviatur-api/
          file: ./backend/aviatur-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build_bk.outputs.digest }}
      
      - name: Build and push frontend
        id: docker_build_fe
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/aviatur-app/
          file: ./frontend/aviatur-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build_fe.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy Backend to Azure Web App
      id: deploy-backend-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'microserviciosud'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_09451c5220fe450eae1800369faff64f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1776f6f0d56d48ae87915fae69cc71fd }}/scvanegasa/backend:${{ github.sha }}'
